### ISSUE TITLE
flask-celery doesn't appear to work

### ISSUE THREAD

**Issue by telking** [ask/flask-celery#13]
python manage.py celeryd
Traceback (most recent call last):
  File "manage.py", line 346, in <module>
    manager.run()
  File "/usr/local/lib/python2.6/dist-packages/flaskext/script.py", line 684, in run
    sys.argv[2:])
  File "/usr/local/lib/python2.6/dist-packages/flaskext/script.py", line 655, in handle
    command.handle(app, _positional_args, *_command_namespace.**dict**)
TypeError: handle() got an unexpected keyword argument 'include'

**Comment by ask** [comment]
If you look at the updated files in the `example` directory, Flask-Celery doesn't use Flask-Script anymore,
but `flask.ext.script` from the `Flask-Script-fix` distribution.

Basically recent versions of Flask-Script broke the API, so it is no longer possible to have custom arguments.
Replace `from flaskext.script` to `from flask.ext.script` and you should be golden!
