### ISSUE TITLE
error: [Errno 111] Connection refused

### ISSUE THREAD

**Issue by 1xch** [ask/flask-celery#19]
So this is confusing to me (posted to http://stackoverflow.com/questions/10855824/celery-flask-error-errno-111-connection-refused as well):

After running through the basic example (runs Aok just plugging the parts into ) I'm trying to integrate this to my own project. Basically, I'm using this below:

So, I have an api  using methodview, in a separate file which I import to my app and register there, and I've stripped this to the basics just to attempt a working version

```
from flask import Blueprint, jsonify, request, session
from flask.views import MethodView
from celery.decorators import task

blueprint = Blueprint('myapi', __name__)

class MyAPI(MethodView):

    def get(self, tag):
        return get_resource.apply_async(tag)

      @task(name="get_task")
      def get_resource(tag):
          pass
```

but I get this when going to the route assigned ( 'localhost:5000/myapiroute/' e.g.), which I do not understand at all:

```

Traceback (most recent call last):
  File "/x/venv/lib/python2.7/site-packages/flask/app.py", line 1518, in __call__
    return self.wsgi_app(environ, start_response)
  File "/x/venv/lib/python2.7/site-packages/flask/app.py", line 1506, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/x/venv/lib/python2.7/site-packages/flask/app.py", line 1504, in wsgi_app
    response = self.full_dispatch_request()
  File "/x/venv/lib/python2.7/site-packages/flask/app.py", line 1264, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/x/venv/lib/python2.7/site-packages/flask/app.py", line 1262, in full_dispatch_request
    rv = self.dispatch_request()
  File "/x/venv/lib/python2.7/site-packages/flask/app.py", line 1248, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/x/venv/lib/python2.7/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/x/venv/lib/python2.7/site-packages/flask/views.py", line 151, in dispatch_request
    return meth(*args, **kwargs)
  File "/x/api/modules/document/document.py", line 14, in get
    return get_document.apply_async(document_tag)
  File "/x/venv/lib/python2.7/site-packages/celery/app/task/__init__.py", line 449, in apply_async
    publish = publisher or self.app.amqp.publisher_pool.acquire(block=True)
  File "/x/venv/lib/python2.7/site-packages/kombu/connection.py", line 657, in acquire
    R = self.prepare(R)
  File "/x/venv/lib/python2.7/site-packages/kombu/pools.py", line 54, in prepare
    p = p()
  File "/x/venv/lib/python2.7/site-packages/kombu/pools.py", line 45, in <lambda>
    return lambda: self.create_producer()
  File "/x/venv/lib/python2.7/site-packages/celery/app/amqp.py", line 265, in create_producer
    pub = self.app.amqp.TaskPublisher(conn, auto_declare=False)
  File "/x/venv/lib/python2.7/site-packages/celery/app/amqp.py", line 328, in TaskPublisher
    return TaskPublisher(*args, **self.app.merge(defaults, kwargs))
  File "/x/venv/lib/python2.7/site-packages/celery/app/amqp.py", line 158, in __init__
    super(TaskPublisher, self).__init__(*args, **kwargs)
  File "/x/venv/lib/python2.7/site-packages/kombu/compat.py", line 61, in __init__
    super(Publisher, self).__init__(connection, self.exchange, **kwargs)
  File "/x/venv/lib/python2.7/site-packages/kombu/messaging.py", line 79, in __init__
    self.revive(self.channel)
  File "/x/venv/lib/python2.7/site-packages/kombu/messaging.py", line 168, in revive
    channel = channel.default_channel
  File "/x/venv/lib/python2.7/site-packages/kombu/connection.py", line 581, in default_channel
    self.connection
  File "/x/venv/lib/python2.7/site-packages/kombu/connection.py", line 574, in connection
    self._connection = self._establish_connection()
  File "/x/venv/lib/python2.7/site-packages/kombu/connection.py", line 533, in _establish_connection
    conn = self.transport.establish_connection()
  File "/x/venv/lib/python2.7/site-packages/kombu/transport/amqplib.py", line 279, in establish_connection
    connect_timeout=conninfo.connect_timeout)
  File "/x/venv/lib/python2.7/site-packages/kombu/transport/amqplib.py", line 89, in __init__
    super(Connection, self).__init__(*args, **kwargs)
  File "/x/venv/lib/python2.7/site-packages/amqplib/client_0_8/connection.py", line 129, in __init__
    self.transport = create_transport(host, connect_timeout, ssl)
  File "/x/venv/lib/python2.7/site-packages/amqplib/client_0_8/transport.py", line 281, in create_transport
    return TCPTransport(host, connect_timeout)
  File "/x/venv/lib/python2.7/site-packages/amqplib/client_0_8/transport.py", line 85, in __init__
    raise socket.error, msg
error: [Errno 111] Connection refused

-->

```

The example stuff I worked into my project still works, but this doesn't. Why doesn't this want to use the redis instance? I'm missing importing something or there is something wierd going on I can't process right now because I don't know what I'm doing exactly, yet.

**Comment by 1xch** [comment]
I set up a simplified version that focuses on the problem for me here: https://github.com/thrisp/flask-celery-problem.

As far as I can tell, the example items work, but what parts I've added not and I cannot determine why at the moment.

**Comment by 1xch** [comment]
From what I can determine, BROKER_TRANSPORT = 'redis', is an important setting. Setting this allowed me to move forward, without that it was looking for an ampq backend. I can't say why exactly this setting was crucial between the example functions and my own functions, yet.

**Comment by ask** [comment]
Hey @thrisp,

You're importing `@task` from `celery.decorators` and you shouldn't do that with Flask.

When using Flask you should create a custom Celery instance:

```
from flaskext import Celery

celery = Celery(your_flask_app)


@celery.task
def get_resource(tag):
    pass
```

**Comment by ask** [comment]
In the next Celery version (2.6) you won't even have to use Flask-Celery, just:

```
from celery import Celery


celery = Celery(broker="redis://")

@celery.task
def get_resource(tag):
    pass

if __name__ == "__main__":
    celery.start()
```

If you are just starting out with Celery now, and you are not going to deploy into production for a few weeks,
I'd urge you to use the development version, since it has drastic improvements related to Flask support.

To install the development version do:

```
pip install https://github.com/ask/billiard/zipball/master
pip install https://github.com/ask/kombu/zipball/master
pip install https://github.com/ask/celery/zipball/master
```

And read the new getting started tutorial:
http://ask.github.com/celery/getting-started/first-steps-with-celery.html

And also this is the draft of a more detailed tutorial:
http://ask.github.com/celery/getting-started/next-steps.html

I would love to hear your thoughts on these documents, if there is anything you find confusing
or that you think should be added.

**Comment by 1xch** [comment]
I will try out the development version.

The problem with using @celery.task: if I use that _anywhere_ else but in my app.py I get an error (NameError: name 'celery' is not defined).  I just am not able to get that across my entire set of files, only in my app.py. That was the first solution I discovered. How do I make the `celery` created available throughout?

**Comment by 1xch** [comment]
ok, trying the newer version: much smoother so far.

**Comment by 1xch** [comment]
Much, much smoother.

I've turned my issue into an example here:

https://github.com/thrisp/flask-celery-example

**Comment by yosemitebandit** [comment]
I'm getting the same error when using 2.5.5 on a dev server.  On startup, celeryd shows that it's correctly configured to use redis as a broker.  But when I execute the task, it tries to use the amqp library and fails.  This doesn't happen to me when I test locally.

Any ideas on how to make this work without switching to the development version?

Edit -- I migrated to RC4 and things work well.  Thanks.

**Comment by devangmundhra** [comment]
I have a similar problem when I run the `celery status` or `celery purge` commands.

```
  File "/usr/bin/celery", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/celery/__main__.py", line 30, in main
    main()
  File "/usr/lib/python2.7/site-packages/celery/bin/celery.py", line 81, in main
    cmd.execute_from_commandline(argv)
  File "/usr/lib/python2.7/site-packages/celery/bin/celery.py", line 769, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/usr/lib/python2.7/site-packages/celery/bin/base.py", line 306, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/usr/lib/python2.7/site-packages/celery/bin/celery.py", line 761, in handle_argv
    return self.execute(command, argv)
  File "/usr/lib/python2.7/site-packages/celery/bin/celery.py", line 693, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "/usr/lib/python2.7/site-packages/celery/bin/base.py", line 310, in run_from_argv
    sys.argv if argv is None else argv, command)
  File "/usr/lib/python2.7/site-packages/celery/bin/base.py", line 372, in handle_argv
    return self(*args, **options)
  File "/usr/lib/python2.7/site-packages/celery/bin/base.py", line 269, in __call__
    ret = self.run(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/celery/bin/celery.py", line 472, in run
    replies = I.run('ping', **kwargs)
  File "/usr/lib/python2.7/site-packages/celery/bin/celery.py", line 324, in run
    return self.do_call_method(args, **kwargs)
  File "/usr/lib/python2.7/site-packages/celery/bin/celery.py", line 346, in do_call_method
    callback=self.say_remote_command_reply)
  File "/usr/lib/python2.7/site-packages/celery/bin/celery.py", line 385, in call
    return getattr(i, method)(*args)
  File "/usr/lib/python2.7/site-packages/celery/app/control.py", line 99, in ping
    return self._request('ping')
  File "/usr/lib/python2.7/site-packages/celery/app/control.py", line 70, in _request
    timeout=self.timeout, reply=True,
  File "/usr/lib/python2.7/site-packages/celery/app/control.py", line 306, in broadcast
    limit, callback, channel=channel,
  File "/usr/lib/python2.7/site-packages/kombu/pidbox.py", line 283, in _broadcast
    chan = channel or self.connection.default_channel
  File "/usr/lib/python2.7/site-packages/kombu/connection.py", line 755, in default_channel
    self.connection
  File "/usr/lib/python2.7/site-packages/kombu/connection.py", line 740, in connection
    self._connection = self._establish_connection()
  File "/usr/lib/python2.7/site-packages/kombu/connection.py", line 695, in _establish_connection
    conn = self.transport.establish_connection()
  File "/usr/lib/python2.7/site-packages/kombu/transport/pyamqp.py", line 112, in establish_connection
    conn = self.Connection(**opts)
  File "/usr/lib/python2.7/site-packages/amqp/connection.py", line 165, in __init__
    self.transport = create_transport(host, connect_timeout, ssl)
  File "/usr/lib/python2.7/site-packages/amqp/transport.py", line 294, in create_transport
    return TCPTransport(host, connect_timeout)
  File "/usr/lib/python2.7/site-packages/amqp/transport.py", line 95, in __init__
    raise socket.error(last_err)
socket.error: [Errno 111] Connection refused
```

I am using SQS BROKER_URL.
The tasks are running fine, but when I want to purge the tasks on a queue (`celery purge -f`), I get the above error.

```
software -> celery:3.1.11 (Cipater) kombu:3.0.18 py:2.7.5
            billiard:3.3.0.17 py-amqp:1.4.5
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.default.Loader
settings -> transport:amqp results:disabled
```

**Comment by marcstreeter** [comment]
I'm getting the same error as devangmundhra , but I'm using mysql:

`$ celery purge`

gives

```
  File "/usr/bin/celery", line 11, in <module>
    sys.exit(main())
  File "/usr/lib64/python2.7/site-packages/celery/__main__.py", line 30, in main
    main()
  File "/usr/lib64/python2.7/site-packages/celery/bin/celery.py", line 81, in main
    cmd.execute_from_commandline(argv)
  File "/usr/lib64/python2.7/site-packages/celery/bin/celery.py", line 769, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/usr/lib64/python2.7/site-packages/celery/bin/base.py", line 307, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/usr/lib64/python2.7/site-packages/celery/bin/celery.py", line 761, in handle_argv
    return self.execute(command, argv)
  File "/usr/lib64/python2.7/site-packages/celery/bin/celery.py", line 693, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "/usr/lib64/python2.7/site-packages/celery/bin/base.py", line 311, in run_from_argv
    sys.argv if argv is None else argv, command)
  File "/usr/lib64/python2.7/site-packages/celery/bin/base.py", line 373, in handle_argv
    return self(*args, **options)
  File "/usr/lib64/python2.7/site-packages/celery/bin/base.py", line 270, in __call__
    ret = self.run(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/celery/bin/celery.py", line 472, in run
    replies = I.run('ping', **kwargs)
  File "/usr/lib64/python2.7/site-packages/celery/bin/celery.py", line 324, in run
    return self.do_call_method(args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/celery/bin/celery.py", line 346, in do_call_method
    callback=self.say_remote_command_reply)
  File "/usr/lib64/python2.7/site-packages/celery/bin/celery.py", line 385, in call
    return getattr(i, method)(*args)
  File "/usr/lib64/python2.7/site-packages/celery/app/control.py", line 100, in ping
    return self._request('ping')
  File "/usr/lib64/python2.7/site-packages/celery/app/control.py", line 71, in _request
    timeout=self.timeout, reply=True,
  File "/usr/lib64/python2.7/site-packages/celery/app/control.py", line 307, in broadcast
    limit, callback, channel=channel,
  File "/usr/lib/python2.7/site-packages/kombu/pidbox.py", line 283, in _broadcast
    chan = channel or self.connection.default_channel
  File "/usr/lib/python2.7/site-packages/kombu/connection.py", line 756, in default_channel
    self.connection
  File "/usr/lib/python2.7/site-packages/kombu/connection.py", line 741, in connection
    self._connection = self._establish_connection()
  File "/usr/lib/python2.7/site-packages/kombu/connection.py", line 696, in _establish_connection
    conn = self.transport.establish_connection()
  File "/usr/lib/python2.7/site-packages/kombu/transport/pyamqp.py", line 112, in establish_connection
    conn = self.Connection(**opts)
  File "/usr/lib/python2.7/site-packages/amqp/connection.py", line 165, in __init__
    self.transport = self.Transport(host, connect_timeout, ssl)
  File "/usr/lib/python2.7/site-packages/amqp/connection.py", line 186, in Transport
    return create_transport(host, connect_timeout, ssl)
  File "/usr/lib/python2.7/site-packages/amqp/transport.py", line 299, in create_transport
    return TCPTransport(host, connect_timeout)
  File "/usr/lib/python2.7/site-packages/amqp/transport.py", line 95, in __init__
    raise socket.error(last_err)
socket.error: [Errno 111] Connection refused
```

However if I go directly to the folder where I have my celery app I can type

```
$celery -A  celery_app purge
```

And it gives

```
WARNING: This will remove all tasks from queue: celery.
         There is no undo for this operation!

(to skip this prompt use the -f option)

Are you sure you want to delete all tasks (yes/NO)? yes
No messages purged from 1 queue
```

Any thoughts? Suggestions

**Comment by ask** [comment]
How would it know what broker transport to use if you don't give it the location of the app?

**Comment by marcstreeter** [comment]
Does it always need the location of the app? If so then it might make sense to make the purge option fail with the appropriate error that details the need for purge to be accompanied by application name.  This is coming from a noob's perspective. Thanks for responding -- I take it that the second method is the appropriate way.
