### ISSUE TITLE
celeryev: ImportError: cannot import name OPTION_LIST

### ISSUE THREAD

**Issue by imlucas** [ask/flask-celery#3]
```
$ ./manage.py celeryev -h
Traceback (most recent call last):
  File "./manage.py", line 22, in <module>
    manager.run()
  File "env/lib/python2.6/site-packages/flaskext/script.py", line 684, in run
    sys.argv[2:])
  File "env/lib/python2.6/site-packages/flaskext/script.py", line 644, in handle
    command_parser = command.create_parser(prog + " " + name)
  File "env/lib/python2.6/site-packages/flaskext/script.py", line 181, in create_parser
    for option in self.get_options():
  File "env/src/flask-celery/flaskext/celery.py", line 117, in get_options
    from celery.bin.celeryev import OPTION_LIST
ImportError: cannot import name OPTION_LIST
```

**Comment by ask** [comment]
Update with new changes in Celery master branch.  Closed by 2b87dd55d37c8c3e9fb30891ce7d065ee894fe08. Closed by 2b87dd55d37c8c3e9fb30891ce7d065ee894fe08.  Closed by 2b87dd55d37c8c3e9fb30891ce7d065ee894fe08
