### ISSUE TITLE
camqadm: ImportError: cannot import name OPTION_LIST

### ISSUE THREAD

**Issue by imlucas** [ask/flask-celery#4]
```
$ ./manage.py camqadm
Traceback (most recent call last):
  File "./manage.py", line 22, in <module>
    manager.run()
  File "env/lib/python2.6/site-packages/flaskext/script.py", line 684, in run
    sys.argv[2:])
  File "env/lib/python2.6/site-packages/flaskext/script.py", line 644, in handle
    command_parser = command.create_parser(prog + " " + name)
  File "env/lib/python2.6/site-packages/flaskext/script.py", line 181, in create_parser
    for option in self.get_options():
  File "env/src/flask-celery/flaskext/celery.py", line 144, in get_options
    from celery.bin.camqadm import OPTION_LIST
ImportError: cannot import name OPTION_LIST
```

**Comment by imlucas** [comment]
Now sure when it happened, but this is fixed in latest
